#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 22 12:10:44 2020

@author: peter
"""
import mne

import numpy as np

#%%
data_path = '/my_subjects'
fname_raw = '/home/peter/my_subjects/sub-01_free/meg/sub-01_ses-meg_task-facerecognition_run-01_proc-sss_meg.fif'
raw = mne.io.read_raw_fif(fname_raw,preload=True)
raw.set_eeg_reference('average', projection=True)  # set average reference.
raw.apply_proj()
fs = raw.info['sfreq']
data = raw[:][0][:,0:]
#%%
qq = mne.find_events(raw,stim_channel="STI101")
#%%
#%%
data_path = '/my_subjects'
fname_raw = '/home/peter/my_subjects/sub-02_free/meg/sub-02_ses-meg_task-facerecognition_run-01_proc-sss_meg.fif'
raw = mne.io.read_raw_fif(fname_raw,preload=True)
raw.set_eeg_reference('average', projection=True)  # set average reference.
raw.apply_proj()
fs = raw.info['sfreq']
data = raw[:][0][:,0:]
qq2 = mne.find_events(raw,stim_channel="STI101")